#!/bin/sh
#    duh, a heuristics-based design exploration code.
#    Copyright (C) 2016 Hiromasa Kato <hiromasa at gmail.com>
#
#    This file is part of duh.
#
#    duh is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    duh is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# $Id: Swan 127 2013-05-17 16:35:24Z kato $

D=`dirname $0`

if [ -e $D/PythonEnvironment ]; then
	source $D/PythonEnvironment
else
	PYTHON=python
fi

command=$1
shift

case $command in
LOO)
	script=$D/Utils/LOO/LOO.py
	;;
SOMTrain)
	script=$D/Utils/SOM/SOMTrain.py
	;;
SOMView)
	script=$D/Utils/SOM/SOMView.py
	;;
ANOVA)
	script=$D/Utils/ANOVA/ANOVA.py
	;;
*)
	script=$command
	;;
esac

PYTHONPATH=$D: $PYTHON $script $*

